extends Node

const DEBUG_MODE = true
const BACKGROUND_COLOR = Color("29adff")

const GRAVITY = 100
const PLAYER_TERMINAL_VELOCITY = 100
const PLAYER_WALK_SPEED = 45
const PLAYER_WALK_ACCELERATION = 10
const PLAYER_WALK_DECELERATION = 15
const PLAYER_FALL_ACCELERATION = 5
const PLAYER_FALL_DECELERATION = 5

const TILE_SPIKE_INDEX = 8
const TILE_INACTIVE_SAVE_POINT_INDEX = 9
const TILE_ACTIVE_SAVE_POINT_INDEX = 10
