extends Node

const GAME_SET_STATE = 'GAME_SET_STATE'
const GAME_SET_LEVEL = 'GAME_SET_LEVEL'
const GAME_SET_CAN_MOVE = 'GAME_SET_CAN_MOVE'
const GAME_SET_MOVEMENT_VECTOR = 'GAME_SET_MOVEMENT_VECTOR'
const GAME_SET_MOVE_COUNTER = 'GAME_SET_MOVE_COUNTER'

const PORTAL_PUSH_BACK_QUEUE = 'PORTAL_PUSH_BACK_QUEUE'
const PORTAL_CLEAR_QUEUE = 'PORTAL_CLEAR_QUEUE'
